[package]
name = "git-cli"
version = "0.1.0"
authors = ["Henry Boisdequin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rust-crypto = "0.2.36"
regex = "1.4.3"
lazy_static = "1.4.0"
